
package CapaPresentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frmMaquinaCafe extends javax.swing.JFrame {

    /**
     * Creates new form frmMaquinaCafe
     */
    public frmMaquinaCafe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeer = new javax.swing.JButton();
        txtValorRecolectado = new javax.swing.JTextField();
        btnEscribir = new javax.swing.JButton();
        btnRecibirMoneda = new javax.swing.JButton();
        btnCancelarOperacion = new javax.swing.JButton();
        btnServirProducto = new javax.swing.JButton();
        btnEntregarVuelto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnProducto = new javax.swing.JButton();
        btnIngredientes = new javax.swing.JButton();
        btnDepositoMonedas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        btnLeer.setText("Leer");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        txtValorRecolectado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorRecolectadoActionPerformed(evt);
            }
        });

        btnEscribir.setText("Escribir");
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        btnRecibirMoneda.setText("RecibirMoneda");
        btnRecibirMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecibirMonedaActionPerformed(evt);
            }
        });

        btnCancelarOperacion.setText("CancelarOperacion");
        btnCancelarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarOperacionActionPerformed(evt);
            }
        });

        btnServirProducto.setText("ServirProducto");
        btnServirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServirProductoActionPerformed(evt);
            }
        });

        btnEntregarVuelto.setText("EntregarVuelto");
        btnEntregarVuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarVueltoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("LLAMAR A LAS CLASES HIJAS");

        btnProducto.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnProducto.setText("Producto");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnIngredientes.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnIngredientes.setText("Ingredientes");
        btnIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngredientesActionPerformed(evt);
            }
        });

        btnDepositoMonedas.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnDepositoMonedas.setText("DepositoMonedas");
        btnDepositoMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoMonedasActionPerformed(evt);
            }
        });

        jLabel2.setText("ValorRecolectado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProducto)
                .addGap(18, 18, 18)
                .addComponent(btnIngredientes)
                .addGap(18, 18, 18)
                .addComponent(btnDepositoMonedas)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRecibirMoneda)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarOperacion)
                                .addGap(18, 18, 18)
                                .addComponent(btnServirProducto))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLeer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEscribir))
                                    .addComponent(txtValorRecolectado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)))
                        .addComponent(btnEntregarVuelto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorRecolectado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeer)
                    .addComponent(btnEscribir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecibirMoneda)
                    .addComponent(btnCancelarOperacion)
                    .addComponent(btnServirProducto)
                    .addComponent(btnEntregarVuelto))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProducto)
                    .addComponent(btnIngredientes)
                    .addComponent(btnDepositoMonedas))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Instanciar la clase alumno
    CapaNegocio.MaquinaCafe maquinaCafe = new CapaNegocio.MaquinaCafe();
    
    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        // Leer el contenido de las cajas de texto
        String valorRecolectado = txtValorRecolectado.getText();
        // Llenar los datos a los atributos del objeto a traves de las propiedades
        maquinaCafe.setValorRecolectado(valorRecolectado);
        //Mostrar el Mensaje
        JOptionPane.showMessageDialog(rootPane,"Datos registrados en el objeto");
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        JOptionPane.showConfirmDialog(rootPane, "ValorRecolectado:" + maquinaCafe.getValorRecolectado());
    }//GEN-LAST:event_btnEscribirActionPerformed

    private void btnRecibirMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecibirMonedaActionPerformed
        JOptionPane.showConfirmDialog(rootPane, String.valueOf(maquinaCafe.RecibirMoneda().toString()));
    }//GEN-LAST:event_btnRecibirMonedaActionPerformed

    private void btnCancelarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarOperacionActionPerformed
        JOptionPane.showConfirmDialog(rootPane, String.valueOf(maquinaCafe.CancelarOperacion().toString()));
    }//GEN-LAST:event_btnCancelarOperacionActionPerformed

    private void btnServirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServirProductoActionPerformed
       JOptionPane.showConfirmDialog(rootPane, String.valueOf(maquinaCafe.ServirProducto().toString()));
    }//GEN-LAST:event_btnServirProductoActionPerformed

    private void btnEntregarVueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarVueltoActionPerformed
        JOptionPane.showConfirmDialog(rootPane, String.valueOf(maquinaCafe.EntregarVuelta().toString()));
    }//GEN-LAST:event_btnEntregarVueltoActionPerformed

    private void txtValorRecolectadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorRecolectadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorRecolectadoActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        CapaPresentacion.frmProducto frm = new CapaPresentacion.frmProducto();
        frm.setVisible(true);
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientesActionPerformed
        CapaPresentacion.frmIngrediente frm = new CapaPresentacion.frmIngrediente();
        frm.setVisible(true);
    }//GEN-LAST:event_btnIngredientesActionPerformed

    private void btnDepositoMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoMonedasActionPerformed
        CapaPresentacion.frmDepositoMoneda frm = new CapaPresentacion.frmDepositoMoneda();
        frm.setVisible(true);
    }//GEN-LAST:event_btnDepositoMonedasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMaquinaCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMaquinaCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMaquinaCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMaquinaCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMaquinaCafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarOperacion;
    private javax.swing.JButton btnDepositoMonedas;
    private javax.swing.JButton btnEntregarVuelto;
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnIngredientes;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnRecibirMoneda;
    private javax.swing.JButton btnServirProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtValorRecolectado;
    // End of variables declaration//GEN-END:variables
}
